### PR TITLE
FLUID-5892: Unit test

### PR DESCRIPTION
**Pull request by jobara**
Added unit test for conditional panel in a separated panel.

https://issues.fluidproject.org/browse/FLUID-5892

### CODE REVIEW

**Comment by jobara** [comment]
@waharnum I've added a test, but it still seems to be failing when I'm in  your branch. Could you take a quick look at it and let me know if it's the same issue that you had found earlier, or it's something else (e.g. a problem with my test or a new bug).

New test is in SeparatedPanelPrefsEditor-test.html

**Comment by waharnum** [comment]
@jobara as a quick test, I switched the test over to using the jQueryUI widgets (with an iframe that includes a separately-loaded jQuery, etc) and see the same failure with the test (the `bool` element the test tries to locate doesn't exist), so I don't think it's the same issue we saw before.

By "in your branch" do you mean that the test passes in the current `fluid-project/infusion` master, but fails in my branch?

**Comment by jobara** [comment]
@waharnum it seems that the issue with the test always failing was because the template did not contain the correct class name. I've fixed this and some other issues as well as expanding on the tests. Please let me know if this covers the issue you had experienced.

**Comment by waharnum** [comment]
Looks good @jobara - merging.

**Pull request merged**
